version: 1.0.{build}
build:
  verbosity: minimal
notifications:
- provider: Slack
  auth_token:
    secure: aEpBO36/TvY5kzTe99oI6sW0df4fcJ9vqNBW64H3I4s=
  channel: MimAcher
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Email
  to:
  - cayopdonatti@gmail.com
  - gustavomatozinho@gmail.com
  subject: Build MimAcher
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true