version: 1.0.{build}
before_build:
  - nuget restore
build:
  verbosity: minimal
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: MimAcher
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true